### ISSUE TITLE
Cannot patch unittest.main.os because of how unittest imports main

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#250]
```
What steps will reproduce the problem?

unittest in the standard library provides the test case.  I was trying to patch 
module os that is imported by unittest.main:

    $ python2.7
    >>> import unittest.main
    >>> import mock
    >>> p = mock.patch('unittest.main.os')
    >>> p.getter()
    <class 'unittest.main.TestProgram'>

That is incorrect.  I believe this is because unittest.py imports 
unittest.main.main as main:

    # Top of unittest/__init__.py
    from .main import TestProgram, main

But at the end of unittest/main.py, they wrote:

    # Bottom of unittest/main.py
    main = TestProgram


What is the expected output? What do you see instead?

So when mock._patch.get_original() resolves the name of unittest.main, it gets 
'unittest.main.TestProgram'.  Since the original is wrong, mock._patch.start() 
fails:

>>> p.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mock.py", line 1396, in start
    result = self.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <class 'unittest.main.TestProgram'> does not have the attribute 
'os'


What version of the product are you using? On what operating system?

Python 2.7.5
 
Please provide any additional information below.


```

Original issue reported on code.google.com by `jmcgehe...@gmail.com` on 19 Apr 2015 at 9:39

**Comment by rbtcollins** [comment]
Yeah, I think this is a bug for unittest, not mock.

**Comment by rbtcollins** [comment]
See http://bugs.python.org/issue24629

**Comment by jmcgeheeiv** [comment]
I am at peace with this issue being closed. I add this note just to share what I know.

I used `UnitTest.main` as an example merely because it was the most convenient. While the `UnitTest` project should be encouraged to remove the shadowing, my main point is that `unittest.mock` does not properly handle this situation, while `mox` does.

**Comment by cjw296** [comment]
@jmcgeheeiv - I wonder if there's a relationship between this issue and https://bugs.python.org/issue39551?

**Comment by jmcgeheeiv** [comment]
@cjw296 thanks for your interest. I cannot tell if there is a relationship.

**Comment by mrbean-bremen** [comment]
> However, rumors of mox's demise appear to have been greatly exaggerated.

Well, a few months later it actually  [has been retired](https://opendev.org/openstack/mox3/commit/b22c58fcfcf20cc9044890a6deba3f12d23cf688).

**Comment by davidlbaird** [comment]
Let's reopen this, because I have thousands (like 20,000 at least) of examples of using pyfakefs, unittest and mock.

**Comment by cjw296** [comment]
This package is a rolling backport of [`unittest.mock`](https://github.com/python/cpython/blob/master/Lib/unittest/mock.py). 
As such, any problems you encounter most likely need to be fixed upstream.

Please can you try and reproduce the problem on the latest release of Python 3, including alphas, and replace any import from `mock` with ones from `unittest.mock`.

If the issue still occurs, then please report upstream through https://github.com/python/cpython/issues as it will need to be fixed there so that it can be backported here and released to you.

If not, reply with what you find out and we can re-open this issue.
