### ISSUE TITLE
Requires setuptools >=17.1 to install properly.

### ISSUE THREAD

**Issue by rgammans** [testing-cabal/mock#261]
Mock doesn't load into a debian Jessie virtual env.

See
```shell
$ virtualenv test
cNew python executable in test/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
$ . ./test/bin/activate
(test)$ pip install mock
Downloading/unpacking mock
  Downloading mock-1.1.1.tar.gz (69kB): 69kB downloaded
  Running setup.py egg_info for package mock
    
    Installed /tmp/test/build/mock/pbr-1.2.0-py2.7.egg
    [pbr] Processing SOURCES.txt
    warning: LocalManifestMaker: standard file '-c' not found
    
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking pbr>=0.11 (from mock)
  Downloading pbr-1.2.0.tar.gz (99kB): 99kB downloaded
  Running setup.py egg_info for package pbr
    [pbr] Processing SOURCES.txt
    warning: LocalManifestMaker: standard file '-c' not found
    
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no files found matching 'requirements.txt'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking six>=1.7 (from mock)
  Downloading six-1.9.0.tar.gz
  Running setup.py egg_info for package six
    
    no previously-included directories found matching 'documentation/_build'
Installing collected packages: mock, pbr, six
  Running setup.py install for mock
    [pbr] Reusing existing SOURCES.txt
  Running setup.py install for pbr
    [pbr] Reusing existing SOURCES.txt
    Installing pbr script to /tmp/test/bin
  Running setup.py install for six
    
    no previously-included directories found matching 'documentation/_build'
Successfully installed mock pbr six
Cleaning up...
(test)$ python 
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test/local/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/tmp/test/local/lib/python2.7/site-packages/mock/mock.py", line 83, in <module>
    import funcsigs
ImportError: No module named funcsigs
>>> 

## Having seen issue 257 ..
>>> import six
>>> six.__version__
'1.9.0'
>>> 
```

**Comment by rbtcollins** [comment]
funcsigs is version constrained:
funcsigs;python_version<"3.3"

What python version do you have there, and what setuptools version?

**Comment by rgammans** [comment]
Python 2.7.9 (It is in the python start banner on the report)
Setup tools = 0.9.8  according to __version__ .

It exhibits with  both debian python-setuptools package version 5.5.1-1 and 17.0.1 if that helps.

**Comment by rbtcollins** [comment]
I suspect that that setuptools is too old to support environment markers properly, and is just discarding the version locked dependency (which ends up being passed to setuptools like so:

extras_require = {
 ':python_version<"3.3"': ['funcsigs']
}

If you update your virtualenv to a newer version (12.x should do it I think, though obviously latest is best) then this should work correctly in new venvs (because virtualenv bundles setuptools).

Or you could pip install -U pip wheel setuptools inside the new virtualenv, which will sort that all out.

**Comment by rgammans** [comment]
I had only version of vritualenv (pre- jessie release) so updating that fixed it in Jessie. Clean installs shouldn't have this issue.

In wheezy (oldstable) the "pip install -U pip wheel setuptools" inside the virtualenv works

**Comment by rbtcollins** [comment]
I'm reopening this, hopefully that will stop the dupes.

**Comment by diranged** [comment]
For what its worth, I'm seeing this issue even with `mock==0.1.2`.

```
Traceback (most recent call last):
  File "/mnt/jenkins/workspace/eng-continuous-build-ghe@2/nd/.venv/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/jenkins/workspace/eng-continuous-build-ghe@2/nd/.venv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/jenkins/workspace/eng-continuous-build-ghe@2/nd/.venv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/jenkins/workspace/eng-continuous-build-ghe@2/nd/nd/thrift_to_flume_test.py", line 1, in <module>
    import mock
  File "/mnt/jenkins/workspace/eng-continuous-build-ghe@2/nd/.eggs/mock-1.1.2-py2.7.egg/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/mnt/jenkins/workspace/eng-continuous-build-ghe@2/nd/.eggs/mock-1.1.2-py2.7.egg/mock/mock.py", line 83, in <module>
    import funcsigs
ImportError: No module named funcsigs
```

**Comment by rbtcollins** [comment]
Yes. 1.1.2 added a versioned setup_requires dep on pbr, which handles the bracketisation around the AND expression in the extra environment markers. But since setuptools can't handle upgrading setuptools, I've hesitated to add a versioned dep on that. There's a PR I haven't reviewed yet to make setup.py error itself - I need to do a bit of testing to see what works best.

**Comment by carltongibson** [comment]
For info we  ran into this on Django Compressor django-compressor/django-compressor#633 for Python 3.2. ([See the failing Travis build](https://travis-ci.org/django-compressor/django-compressor/builds/70706580))

Both mock and setuptools didn't properly install. 

Pinning to `mock==1.0.1` resolved the issue.

**Comment by jaraco** [comment]
I think it's a little soon to have a dependency on setuptools 17.1. Setuptools 0.7+ supports environment markers, just not the range markers. How about for now, set the dependency to:

```
funcsigs; python_version == "2.7" or python_version="3.2"
```

Ugly, I know, but then it doesn't rely on a cutting edge setuptools to declare its dependencies properly.

**Comment by rbtcollins** [comment]
Thanks @jaraco thats good feedback :). Looking at Ubuntu, precise, which is still supported, is 0.6.24, so wouldn't support markers. I expect one of the major use cases to be things like travis, which runs on precise by default, so we're still going to be forcing upgrades there. Are there other considerations I need to worry about?

**Comment by jaraco** [comment]
No other considerations come to mind.

**Comment by rbtcollins** [comment]
Ok, I think we have the following choices:
 - pick setuptools features by OS packaging versions LTS releases (RHEL, Ubuntu precise etc)
 - pick setuptools features by version bundled in pip within the stdlib
 - pick setuptools assuming folk will have to upgrade

The first does't give us markers at all, and means we can't do universal wheels. That makes the release process harder.

The second limits us to very recent Pythons.

The last does interact poorly with binary packaged setuptools, but nearly everyone else should be able to upgrade, as setuptools is (IMO) particularly good about backwards compat.

So - I'm going to stick with assuming folk have to upgrade, and having done that pick the features we need and the lowest setuptools version that has them. Since we support 2.6 again, being able to say <= is more important than ever: so I think this is wontfix. 17.1 or bust.
