### ISSUE TITLE
mock 1.1.4 does not work

### ISSUE THREAD

**Issue by Kwpolska** [testing-cabal/mock#288]
mock 1.1.3: pass https://travis-ci.org/getnikola/nikola/jobs/71311802#L607
mock 1.1.4: fail https://travis-ci.org/getnikola/nikola/jobs/71393137#L648

What went wrong?

**Comment by rbtcollins** [comment]
Looks like two related issues, due to one specific change.

1.1.4 restored the behaviour of mock 1.0.1 / Python unittest.mock 3.3: read_data passed to a mock_open can be read from each instance. 1.1.0 through 1.1.3 had the behaviour of unittest.mock in Python 3.4 and 3.5 until http://bugs.python.org/issue21750 was fixed - they'd give you the read_data for the first mock_open, and then empty files for the next and subsequent mock_opens.

Separate mock_opens are (and always were indepedent), so one thing you could do is:
open = MagicMock()
open.side_effect = [mock_open(read_data='file1')(), mock_open(read_data='file2')()]
patch('builtins.open', open)

or something like that.

The second issue, is I think related fallout - in that the write call you're checking isn't on the mock object we capture, because fixing the read_data thing required a new closure, so rather than one Mock with N calls, we have N mocks each of which have their own calls, but something isn't quite linked up properly there.

I think this should be filed upstream at https://bugs.python.org/

**Comment by Kwpolska** [comment]
If it worked in 1.1.3, how come it’s an upstream bug? And why did you introduce API-breaking-changes in a patch version?

**Comment by Kwpolska** [comment]
Also, do you have any real examples on how to fix our failures?

**Comment by rbtcollins** [comment]
Well, it shouldn't have worked in 1.0.1, and clearly I didn't consider it an API breaking change [rather unbreaking, because it was reported as a regression in 1.1.0].

Its an upstream bug because mock is a rolling backport: it was meant to be kept in sync, and we've just gotten caught up with several years development at once.

**Comment by rbtcollins** [comment]
I gave a possible suggestion to fix your tests before, but I haven't looked super closely at your tests to offer more advice, and I'm unlikely to be able to do that until late next week - I have to sleep soon, and then its family time over the weekend, and then I'm on a flight to the US for a week. I suggest pinning your mock for now to unbreak your CI, and then digging in in more detail.

**Comment by Kwpolska** [comment]
I pinned `mock==1.1.3` for the time being. Thank you for your help and fast replies!

**Comment by mriedem** [comment]
This is also impacting openstack:

https://bugs.launchpad.net/nova/+bug/1475661

https://bugs.launchpad.net/ironic/+bug/1475653

I'm going to push a change to block mock<1.1.4.

**Comment by rbtcollins** [comment]
I'm going to revert this and issue a 1.2. There's a clear scenario like so:
```
    def test_mock_write(self):
        # Test exception in file writing write()
        mock_namedtemp = mock.mock_open(mock.MagicMock(name='JLV'))
        with mock.patch('tempfile.NamedTemporaryFile', mock_namedtemp):
            mock_filehandle = mock_namedtemp.return_value
            mock_write = mock_filehandle.write
            mock_write.side_effect = OSError('Test 2 Error')
            def attempt():
                tempfile.NamedTemporaryFile().write('asd')
            self.assertRaises(OSError, attempt)
```

Now this could be more clearly written as a mock using test as:
```
mock_open = mock.MagicMock()
mock_open.return_value.write.side_effect = OSError('Test 2 Error')
mock.patch('tempfile.NamedTemporaryFile', mock_open)
def attempt():
    tempfile.NamedTemporaryFile().write('asd')
self.assertRaises(OSError, attempt)
```

So the question becomes: should mock_open, which is a special help for *simple* use of a file system also support arbitrary manipulations.

I think it should, thus I'm going to revert this, add this note into the upstream bug and figure out a way to get both things achieved.

**Comment by rbtcollins** [comment]
http://bugs.python.org/issue21750

**Comment by rbtcollins** [comment]
1.2.0 up with this fixed; future work tracked on 21750.
