### ISSUE TITLE
Mock method disappeared in new version

### ISSUE THREAD

**Issue by rubik** [testing-cabal/mock#302]
Until `mock==1.0.1` Mock objects had a `assert_called_twice_with` method. In later versions it has disappeared from the code, and I cannot find it in the documentation either. What's odd is that the code that makes use of it works in Python 3.3 and 3.4. That means it's there somewhere in those versions but it's not present in newer versions of mock!

**Comment by rbtcollins** [comment]
No, it never did:
```
mock$ git log -p | grep assert_called_twice_with
mock$ 
```

What you had was the classic thing fixed in Python 3.5: you had a method call that was actually just another Mock attribute being created on the fly, and your tests were invalid. Sorry :(, but thats why we made it error on assert* attributes that don't exist rather than mocking them.

**Comment by rubik** [comment]
Wow, that was nasty. Thanks for clearing it up for me!
