### ISSUE TITLE
Using isinstance and mocking datetime

### ISSUE THREAD

**Issue by ccorcos** [testing-cabal/mock#355]
```py
from datetime import datetime
from mock import patch
dt = patch('my_module.datetime', spec=datetime).start()
dt.__class__
# datetime.datetime
dt(1970, 1, 1).__class__
# datetime.datetime
dt.fromtimestamp(1461004080000L).__class__
# mock.MagicMock
```

Not sure how fromtimestamp ends up returning a MagicMock instance... but its causing me some troubles.

**Comment by ccorcos** [comment]
Another related issue here: from within my_module, 

```py
isinstance(datetime.now(), datetime)
# TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by rbtcollins** [comment]
Thats the behaviour of patch - you've made datetime a MagicMock, and everything it returns is another MagicMock unless you've overridden the return value.

For the second case, you'll need to preserve the type you want to check against somewhere - but note that .now(), when mocked, is going to be returning a MagicMock itself.

You might prefer using stackexchange or something for usage questions, since there's only a couple of developers watching the bugtracker here ;).

Anyhow, I don't see a bug, so closing this issue,
