### ISSUE TITLE
Comparing sqla.types

### ISSUE THREAD

**Issue by KaiDriessen** [testing-cabal/mock#416]
Comparing sqla.types seems to be causing some problems. Output (-vv):

to_sql_mock.assert_called_once_with(table, mysql_connection.engine, if_exists='append', dtype=dtypes)
E AssertionError: Expected call: to_sql('table', 'engine', dtype={'var_name': VARCHAR(length=255)}, if_exists='append')
E Actual call: to_sql('table', 'engine', dtype={'var_name': VARCHAR(length=255)}, if_exists='append')
E
E pytest introspection follows:
E
E Kwargs:
E assert {'dtype': {'v...ts': 'append'} == {'dtype': {'va...ts': 'append'}
E Common items:
E {'if_exists': 'append'}
E Differing items:
E {'dtype': {'var_name': VARCHAR(length=255)}} != {'dtype': {'var_name': VARCHAR(length=255)}}
E Full diff:
E {'dtype': {'var_name': VARCHAR(length=255)}, 'if_exists': 'append'}
Replacing the VARCHAR type with any other basic type fixes the problem. The type VARCHAR is obtained as follows:

import sqlalchemy as sqla
sqla.types.VARCHAR(length=255)

**Comment by rbtcollins** [comment]
@zzzeek any thoughts?

**Comment by zzzeek** [comment]
SQLAlchemy type objects don't have an `__eq__()` method, because comparing types is usually a matter of context.  The most common case is comparing a type object that's in a model to one that comes from reflection (i.e. autoload), which usually means you have a type like sqlalchemy.types.VARCHAR on one side and sqlalchemy.dialects.mysql.VARCHAR on the other; the latter type is more specific to MySQL and includes additional options.    It's also not clear if a hypothetical `__eq__()` would only compare options that render the DDL output of the type, like "length" for VARCHAR, or internal options as well like "convert_unicode=True".  Or if the equality comparison would be strict about DDL modifiers, if I had sqlalchemy.types.VARCHAR(255) and compared it to sqlalchemy.dialects.mysql.VARCHAR(255, national=True), do we care about the "national" qualifier that is MySQL-specific.  Sometimes databases create additional options on a type by default that come back in reflection even if they weren't set up in the model. 

so basically if I were to add an `__eq__()` it's likely people would keep disagreeing on what this `__eq__()` should be comparing and what it shouldn't be, as comparison of a model-specified type to a database-returned type object is more often than not what people are looking to do.

SQLAlchemy test suite often compares what's known as the "type affinity" of two types just to get a basic sanity check, this is available via the ._type_affinity attribute, and for VARCHAR it would be the sqlalchemy.types.String class, for INT it would be the sqlalchemy.types.Integer class.   this is a very coarse grained comparison (and even then there are still edge cases where it has an ambiguous decision to make, like SQLite DateTime is actually a string, does that compare to a String? )

In Alembic, the autogenerate system has an evolving set of more in-depth type comparison rules, which are suited towards the use case of comparing in-model datatypes to reflected datatypes, so here we are trying to compare the types with a strong notion of DDL.

For comparison of in-model datatypes to other in-model datatypes, in-model datatypes tend to live on Column objects which are affixed to a Table, all of which follows a pretty singleton-ish pattern, so comparison via `==` works because the comparison is a type instance to itself.   Copies of tables and columns are created using the `table.tometadata()` method which in most cases does not copy the type object at all, it's the same type.  So again comparison via `==` works.   

So, if here we have a case of in-model VARCHAR compared to another in-model VARCHAR that is apparently not affixed to the same expression, that's actually a pretty odd use case.   Comparison of expressions that are different, but result in the same SQL, tends to not work anyway, if I had "column('x', String(50)) == 5" as an expression and tried to compare to "column('x', String(50)) == 5", I'd get a SQL comparison object whos `__bool__()` method evaluates to False.

So....I can't guess what your use case here is that you need to compare plain  sqlalchemy.types.VARCHAR() to another one.

so there you have it...thoughts !

**Comment by cjw296** [comment]
No followup from @KaiDriessen so closing.
