### ISSUE TITLE
TypeError: unhashable type: '_ANY'.

### ISSUE THREAD

**Issue by byohay** [testing-cabal/mock#465]
Starting from mock 3.0.0, some of the tests we have failed because of this error:
`TypeError: unhashable type: '_ANY'`.

Reproduction is very simple:

```py
from mock import ANY
{ANY}
```

And the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: '_ANY'
```

**Comment by cjw296** [comment]
Can you describe what you real world use case for this is?
Also, what happens if you try Python 3.7?

**Comment by tirkarthi** [comment]
I could see a note on b7a77db8b4d4ae34101b2de810f41c2371c2170e .

```python
# foo.py
class _ANY(object):
    "A helper object that compares equal to everything."

    def __eq__(self, other):
        return True

    def __ne__(self, other):
        return False

    def __repr__(self):
        return '<ANY>'

ANY = _ANY()
```

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
>>> {foo.ANY}
set([<ANY>])
```

Add `__hash__ = None` in the commit that seems to be not present in 2.0.0 and there is the reported error.

```python
# foo.py
class _ANY(object):
    "A helper object that compares equal to everything."

    def __eq__(self, other):
        return True

    def __ne__(self, other):
        return False

    def __repr__(self):
        return '<ANY>'

    __hash__ = None

ANY = _ANY()
```

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
>>> {foo.ANY}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: '_ANY'
```

On CPython master :

```
./python.exe
Python 3.8.0a4+ (heads/master-dirty:b1c3167c23, May  8 2019, 10:26:11)
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest import mock
>>> {mock.ANY}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: '_ANY'
```

**Comment by cjw296** [comment]
Sorry, I don't understand "Add __hash__ = None in the commit that seems to be not present in 2.0.0 and there is the reported error."

**Comment by tirkarthi** [comment]
Before b7a77db8b4d4ae34101b2de810f41c2371c2170e the statement `__hash__ = None` was not present and hence mock 2.0.0 had `{ANY}` executed without `TypeError`. But in mock 3.0+ with the linked commit added `__hash__ = None` which causes this error. Since definition of _ANY is a simple class I have added the code as standalone file (foo.py) to illustrate the difference and noted `__hash__ = None` could have caused this. There could be some Python 2/3 reason for the commit and it sadly has no test.

**Comment by byohay** [comment]
@cjw296 it also happens in Python 3.7.

**Comment by cjw296** [comment]
@byohay - okay, but was that using `unittest.mock` or the `mock` backport?

Also, please can you explain your real-world use case for putting `ANY` in a set? That seems unusual, if not odd...

**Comment by tirkarthi** [comment]
From the PR #378 

> Python 3 now requires you to implement __hash__ if you implement __eq__. See docs.python.org/3.6/reference/datamodel.html#object.%5F%5Fhash%5F%5F .

In Python 3 `__hash__` needs to be implemented when `__eq__` is implemented and without which it throws `TypeError` and has been the behavior upstream. In Python 2 `__hash__` is implemented by itself with `__eq__`. In the backport using `python2 -3 mock.py` would have issued the below warning. So to ensure the behavior is same in Python 2 and 3 backport's behavior was changed to set `__hash__ = None` so that mock backport under Python 2 also throws `TypeError` like upstream but from a backport user point of view using Python 2 it's a change in behavior that ANY is now not hashable.

```
$ cat bar.py
class Foo(object):

    def __eq__(self, other):
        return True

Foo()
$ python2 -3 bar.py
bar.py:1: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Foo(object):
```

**Comment by byohay** [comment]
@cjw296 sure. I dug dipper and found the cause

**Comment by byohay** [comment]
@cjw296 sure. I dug dipper and found why it needed to be hashable:

**Comment by cjw296** [comment]
Okay, but why use `ANY` there? Why not a [`Sentinel`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.sentinel) or just an `object()`?

**Comment by byohay** [comment]
Initially I thought that it could spare me some variables if I could just set some of the values in the `namedtuple` to `ANY`. However, it seems that I was mistaken. That is, putting `ANY` inside a `set` won't work:
```py
from collections import namedtuple
from mock imoprt ANY

Foo = namedtuple("Foo", ["one", "two", "three", "four", "five"])

foo_instance = Foo(ANY,ANY,3,ANY,ANY)
another_foo_instance = Foo(1,2,3,4,5)

foo_instance == another_foo_instance  # True
{foo_instance} == {another_foo_instance}  # False
```
Which is probably caused by the fact that the two instances' hashes are different. 

So `sentinel` and `object()` are indeed good enough.

**Comment by cjw296** [comment]
Great, I think we'll have to accept that `ANY` being unhashable is a deliberate choice.
