### ISSUE TITLE
Syntax Error in 4.0.0

### ISSUE THREAD

**Issue by chrisconlon-klaviyo** [testing-cabal/mock#478]
There is a syntax error [here](https://github.com/testing-cabal/mock/blob/ea9f71536da0ce3bd31e31b5f428f3495c6ab0dc/mock/mock.py#L575) in v4.0.0 that a build of mine accidentally pulled in after the release got published.

I'll see if I can open a PR with a fix, but I'm starting here just to flag it.

**Comment by cjw296** [comment]
What version of Python are you using?

**Comment by chrisconlon-klaviyo** [comment]
This was on a 2.7 build. I drafted a PR here: https://github.com/testing-cabal/mock/pull/479

Not sure of this projects contribution guidelines.

**Comment by cjw296** [comment]
Mock is no longer compatible with Python 2.

Please see the [documentation](https://mock.readthedocs.io/en/latest/#python-version-compatibility) and the [release metadata](https://pypi.org/project/mock/).

I'd suggest upgrading your installation tools so that they respect the metadata in pypi, and get off Python 2 as soon as possible.
