### ISSUE TITLE
Should the backports follow upstream releases? instead of alpha/beta/rcs.

### ISSUE THREAD

**Issue by doublethefish** [testing-cabal/mock#483]
The 4.0.0 release was a backport of a CPython alpha release, introducing all the risk of doing that to anyone consuming this repo (and possibly causing the maintainers more work as they might need to deal with the issues found).

Is it a good idea for major release, like "4.0.0", to follow an alpha upstream, instead of a stable release e.g. Python3.9 when it eventually leaves alpha.

The suggestion is that, at the time or writing, the latest release of `import mock` should actually be the same as Python3.8.1's, with an optional 4.0.0 alpha/unstable version that follows the Python3.9alpha.

It is likely to reduce the maintainer's work if that was process was followed.

If the above isn't desired then it would be really useful to clarify what the policy is for backporting CPython versions e.g. specifying that the backport module _intentionally_ follows the CPython alpha releases and what the reasons for doing that are.

Once again, a massive thanks for the fast turnaround on this morning's issues.

**Comment by cjw296** [comment]
The backport is strictly semver, tracking cpython master:
- As backwards incompatible changes arrive, we bump major.
- New backwards compatible feature? we bump minor.
- Bugfix? bump third point.

See release.py in this repo.

Release frequency is as maintainer time is available with the intention of soliciting feedback on upstream changes sooner rather than later.

I'm afraid, as far as "maintainer's work" is concerned, this is as lightweight as I can get it.

**Comment by doublethefish** [comment]
So, the backport _should_ follow alpha/beta/rcs and not stable, qa'd releases. Ok, got it.

Should we reconsider that policy for the future?

At the risk of flogging a dead horse, the 4.0.0 release, should probably have been semantically versioned to match the "pre-release" status of the upstream. The pre-release extensions to semantic-versions are exactly for this use-case. https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions

**Comment by cjw296** [comment]
backport follows master, master is stable modulo bugs, which we want to find sooner rather than later.

No, to ease the maintenance burden of this backport that is not a policy that should be reconsidered. (it's hard enough tracking one upstream master branch).

No, 4.0 is a production, final release. Software has bugs, I'm afraid we all need to accept that ;-)
